server:
  port: 9091

spring:
  application:
    name: spring-boot-facebook-oauth-demo

security:
  oauth2:
    client:
      clientId: 130572119100737
      clientSecret: 06431fb0c87f603c02491fa7f19cca0f
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
